import { useState } from "react";
import { motion } from "framer-motion";
import { Star, BarChart3, GraduationCap, TrendingUp, CreditCard, PiggyBank, ListChecks } from "lucide-react";
import { Card } from "@/components/ui/Card";
import { Button } from "@/components/ui/Button";
import { useQuery } from "@tanstack/react-query";
import { useAuth } from "@/hooks/useAuth";
import { IAgentOutput } from "@/types";
import { useLocation } from "wouter";
import { InsightDetailModal } from "@/components/InsightDetailModal";

export default function AllInsights() {
  const { user } = useAuth();
  const userId = user?.id || localStorage.getItem("userId");
  const [, navigate] = useLocation();

  // State to manage the modal
  const [selectedInsightId, setSelectedInsightId] = useState<string | null>(null);

  // Fetch all insights for the user
  const { data: insights = [], isLoading } = useQuery<IAgentOutput[]>({
    queryKey: [`/api/agent-outputs/user`, userId], 
    enabled: !!userId,
  });

  const getInsightIcon = (agentType: string) => {
    switch (agentType) {
      case "master": return Star;
      case "budget_planner": return BarChart3;
      case "financial_educator": return GraduationCap;
      case "investment_advisor": return TrendingUp;
      case "debt_optimizer": return CreditCard;
      case "income_expense_analyzer": return PiggyBank;
      default: return Star;
    }
  };

  const getPriorityColor = (priority: string) => {
    switch (priority?.toLowerCase()) {
      case "high": return "hsl(0 84% 60%)";
      case "medium": return "hsl(46 95% 53%)";
      case "low": return "hsl(158 64% 52%)";
      default: return "hsl(221 83% 53%)";
    }
  };

  // Handles the "Take Action" button click
  const handleAction = (e: React.MouseEvent, actionType: string | undefined, insightId: string) => {
    e.stopPropagation(); // Stop click from opening the modal
    if (!actionType) return;

    const actionRouteMap: Record<string, string> = {
      "invest": "/portfolio",
      "review_budget": "/scenarios",
      "start_learning": "/financial-story",
      "optimize_spending": "/scenarios",
      "manage_debt": "/scenarios",
      "increase_savings": "/scenarios",
      "review": "/dashboard"
    };
    const route = actionRouteMap[actionType] || "/dashboard";
    navigate(route);
  };

  const handleCardClick = (insightId: string) => {
    setSelectedInsightId(insightId);
  };

  return (
    <main className="flex-1 p-6 overflow-auto" data-testid="all-insights-page">
      <motion.div
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        className="max-w-4xl mx-auto"
      >
        <div className="mb-8">
          <h1 className="text-3xl font-bold mb-2">All AI-Generated Insights</h1>
          <p className="text-muted-foreground">
            Review all insights and detailed plans generated by the AI agents.
          </p>
        </div>

        <div className="space-y-4" data-testid="insights-container">
          {isLoading && (
            <div className="text-center py-8 text-muted-foreground">Loading insights...</div>
          )}
          {!isLoading && insights.length === 0 ? (
            <Card className="p-6 text-center text-muted-foreground">
              No insights available yet. Try asking the AI for financial advice from the dashboard!
            </Card>
          ) : (
            // We map ALL insights here, no .slice()
            insights.map((insight) => {
              const Icon = getInsightIcon(insight.agentType);
              const color = getPriorityColor(insight.priority || "medium");
              const isHighPriority = insight.priority?.toLowerCase() === "high";
              const actionType = insight.outputData?.actionType || insight.outputData?.action;

              return (
                <motion.div
                  key={insight.id}
                  initial={{ opacity: 0, x: -20 }}
                  animate={{ opacity: 1, x: 0 }}
                  transition={{ delay: 0.1 }}
                  className={`rounded-lg p-4 cursor-pointer hover:shadow-md transition-shadow ${
                    isHighPriority
                      ? "bg-destructive/10 border border-destructive/30"
                      : "bg-accent"
                  }`}
                  data-testid={`insight-${insight.id}`}
                  onClick={() => handleCardClick(insight.id)} 
                >
                  <div className="flex items-start space-x-3">
                    <div
                      className="w-8 h-8 rounded-full flex items-center justify-center flex-shrink-0"
                      style={{ backgroundColor: color }}
                    >
                      <Icon className="w-4 h-4 text-white" />
                    </div>
                    <div className="flex-1">
                      <div className="font-medium text-sm mb-1">
                        {insight.outputData?.title || "Financial Insight"}
                      </div>
                      <div className="text-sm text-muted-foreground mb-3">
                        {insight.outputData?.description || "Analysis completed"}
                      </div>
                      {insight.actionable && actionType && (
                        <Button
                          size="sm"
                          onClick={(e) => handleAction(e, actionType, insight.id)}
                          style={{
                            backgroundColor: color,
                            color: isHighPriority ? 'white' : 'black'
                          }}
                          className="text-white hover:opacity-90"
                          data-testid={`button-${actionType}`}
                        >
                          {actionType === "invest" ? "View Portfolio" :
                          actionType === "review_budget" ? "Review Budget" :
                          actionType === "start_learning" ? "Start Learning" :
                          actionType === "optimize_spending" ? "Optimize Spending" :
                          actionType === "manage_debt" ? "Manage Debt" :
                          actionType === "increase_savings" ? "Increase Savings" :
                          "Take Action"}
                        </Button>
                      )}
                    </div>
                  </div>
                </motion.div>
              );
            })
          )}
        </div>

        {/* Render the modal for showing details */}
        <InsightDetailModal
          isOpen={!!selectedInsightId}
          onClose={() => setSelectedInsightId(null)}
          insightId={selectedInsightId}
        />
      </motion.div>
    </main>
  );
}